#NAME: Xian Kai Ng,Xilai Zhang
#EMAIL: ngxiankai286@gmail.com,xilaizhang@g.ucla.edu
#ID: 204785637,804796478

default:

	cp lab3b.py lab3b
	chmod u+x lab3b.py lab3b

dist: default
	tar -czvf lab3b-804796478.tar.gz README Makefile lab3b.py

clean:
	rm -rf lab3b lab3b-804796478.tar.gz
